### ISSUE TITLE
Issues with linking on macOS

### ISSUE THREAD

**Issue by CenTdemeern1** [wiiuse/wiiuse#144] opened 2024-02-12 01:52 UTC
I'm working on a project that involves creating new Rust bindings for WiiUse (`wiiuse-sys` doesn't work), but it seems that linking certain OS frameworks doesn't work on macOS.

Seeing references to IOBluetooth etc, I googled part of my linker log and found [a StackOverflow post](https://stackoverflow.com/questions/21246608/compiling-a-c-library-for-use-with-a-python-wrapper-on-mac-osx-10-8) from 2014 with an answer from 2016 that mentions adding something to the CMakeLists.

Because it's old, I figured I'd check, and sure enough I could already find something similar in the current CMakeLists:

https://github.com/wiiuse/wiiuse/blob/90951be9b4699194b5dd8f4134eedcbfe96cbbee/src/CMakeLists.txt#L65-L80

So now I'm stumped. This kind of seems like a bug because of the aforementioned fix already being implemented.
I'm not all too experienced with CMake and stuff, any ideas?

<details>
<summary>My linker log (hidden by default for your viewing pleasure)</summary>

```
ld: Undefined symbols:
            _IOBluetoothNSStringFromDeviceAddress, referenced from:
                -[WiiuseDeviceInquiry collectResultsOf:] in libwiiuse.a[16](os_mac_find.m.o)
            _NSDefaultRunLoopMode, referenced from:
                -[WiiuseWiimote waitForIncomingData:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseDeviceInquiry wait] in libwiiuse.a[16](os_mac_find.m.o)
            _OBJC_CLASS_$_IOBluetoothDeviceInquiry, referenced from:
                 in libwiiuse.a[16](os_mac_find.m.o)
            _OBJC_CLASS_$_IOBluetoothHostController, referenced from:
                 in libwiiuse.a[16](os_mac_find.m.o)
            _OBJC_CLASS_$_NSAutoreleasePool, referenced from:
                 in libwiiuse.a[14](os_mac.m.o)
            _OBJC_CLASS_$_NSData, referenced from:
                 in libwiiuse.a[14](os_mac.m.o)
            _OBJC_CLASS_$_NSDate, referenced from:
                 in libwiiuse.a[14](os_mac.m.o)
            _OBJC_CLASS_$_NSLock, referenced from:
                 in libwiiuse.a[14](os_mac.m.o)
            _OBJC_CLASS_$_NSMutableArray, referenced from:
                 in libwiiuse.a[14](os_mac.m.o)
            _OBJC_CLASS_$_NSObject, referenced from:
                _OBJC_CLASS_$_WiiuseWiimote in libwiiuse.a[14](os_mac.m.o)
                _OBJC_CLASS_$_WiiuseDisconnectionMessage in libwiiuse.a[14](os_mac.m.o)
                _OBJC_CLASS_$_WiiuseReceivedData in libwiiuse.a[14](os_mac.m.o)
                _OBJC_CLASS_$_WiiuseDeviceInquiry in libwiiuse.a[16](os_mac_find.m.o)
            _OBJC_CLASS_$_NSRunLoop, referenced from:
                 in libwiiuse.a[14](os_mac.m.o)
            _OBJC_METACLASS_$_NSObject, referenced from:
                _OBJC_METACLASS_$_WiiuseWiimote in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseWiimote in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseReceivedData in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseReceivedData in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseDisconnectionMessage in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseDisconnectionMessage in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseDeviceInquiry in libwiiuse.a[16](os_mac_find.m.o)
                _OBJC_METACLASS_$_WiiuseDeviceInquiry in libwiiuse.a[16](os_mac_find.m.o)
                ...
            __objc_empty_cache, referenced from:
                _OBJC_CLASS_$_WiiuseWiimote in libwiiuse.a[14](os_mac.m.o)
                _OBJC_CLASS_$_WiiuseDisconnectionMessage in libwiiuse.a[14](os_mac.m.o)
                _OBJC_CLASS_$_WiiuseReceivedData in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseWiimote in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseReceivedData in libwiiuse.a[14](os_mac.m.o)
                _OBJC_METACLASS_$_WiiuseDisconnectionMessage in libwiiuse.a[14](os_mac.m.o)
                _OBJC_CLASS_$_WiiuseDeviceInquiry in libwiiuse.a[16](os_mac_find.m.o)
                ...
            _objc_alloc, referenced from:
                -[WiiuseWiimote initWithPtr:device:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote l2capChannelData:data:length:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseReceivedData initWithBytes:length:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseDeviceInquiry collectResultsOf:] in libwiiuse.a[16](os_mac_find.m.o)
                _wiiuse_os_find in libwiiuse.a[16](os_mac_find.m.o)
            _objc_alloc_init, referenced from:
                -[WiiuseWiimote initWithPtr:device:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote disconnected:fromDevice:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote waitForIncomingData:] in libwiiuse.a[14](os_mac.m.o)
                _wiiuse_os_connect_single in libwiiuse.a[15](os_mac_interface.m.o)
                _wiiuse_os_read in libwiiuse.a[15](os_mac_interface.m.o)
                _wiiuse_os_write in libwiiuse.a[15](os_mac_interface.m.o)
                _wiiuse_os_find in libwiiuse.a[16](os_mac_find.m.o)
                ...
            _objc_msgSend, referenced from:
                 in objc-stubs-file
            _objc_msgSendSuper2, referenced from:
                -[WiiuseWiimote initWithPtr:device:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote dealloc] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseReceivedData initWithData:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseReceivedData dealloc] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseDeviceInquiry initWithMemory:maxDevices:timeout:] in libwiiuse.a[16](os_mac_find.m.o)
            _objc_release, referenced from:
                -[WiiuseWiimote dealloc] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote dealloc] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote dealloc] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote dealloc] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote dealloc] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote disconnectChannel:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote disconnect] in libwiiuse.a[14](os_mac.m.o)
                ...
            _objc_retain, referenced from:
                -[WiiuseWiimote initWithPtr:device:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseWiimote connectChannel:PSM:] in libwiiuse.a[14](os_mac.m.o)
                -[WiiuseReceivedData initWithData:] in libwiiuse.a[14](os_mac.m.o)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
</details>

**Comment by janoc** [comment] 2024-02-12 11:12
Hello, 

Unfortunately, no idea :disappointed: The CI compiles it on Mac without issues, I have just triggered it by hand to make sure it is still building and it has passed. 

I am not a Mac user and don't have an OS X machine on hand anywhere to be able to help you. I suggest you look carefully at our CMake files for Mac, perhaps check your Xcode installation and that you have all the required frameworks installed. 

I am not sure @rpavlik can help you either, I don't think she has a Mac on hand either.

Sorry :man_shrugging:

**Comment by CenTdemeern1** [comment] 2024-02-13 09:20
Seems I forgot to reply, whoops
I tried both building wiiuse itself (the examples) and I'm also trying to build my own wrappers
Building the examples seems to work though they don't seem to work when I actually run them(?)
The log from earlier is from building my own wrappers. I have the frameworks and stuff installed. I have no clue what I am doing and I'm not sure how I can link against them myself and at this point I'm considering just giving up

**Comment by janoc** [comment] 2024-02-13 10:09
That sounds like a big mess. 

Try to do it one step at a time, i.e. first make sure that Wiiuse is building and working for you. The SDL example may not work for you but the normal terminal one probably should work even on Mac. Just don't run it from Finder by clicking on it, it is a terminal application!

>The log from earlier is from building my own wrappers. 

Well, sorry then it is impossible to help you without knowing exactly how you have your things set up (please, don't copy your project here, it is out of scope here). 

Most likely your problem has nothing to do with Wiiuse whatsoever but with how you are linking your wrappers (or not) against the required OS X frameworks, namely the IOBluetooth one, judging from the error messages. It is not enough to link against Wiiuse alone. If  you use the wiiuse CMake target exported by Wiiuse CMake project then this should be added automatically for you - that's what the CMakeLists.txt snippet you have posted above actually does. If not, then you are on your own and you must take care of that yourself.

If you are using CMake then I suggest going through the tutorial first to understand what are you even looking for:
https://cmake.org/cmake/help/latest/guide/tutorial/index.html

If you are using Cargo to build this (since you are building a Rust wrapper), then no idea. I have only a passing knowledge of Rust and I have never used it on Mac, so I can't help you there.

Either way, trying to "wing it" somehow without understanding what are you doing is not a way how to achieve anything meaningful.

Good luck!

**Comment by CenTdemeern1** [comment] 2024-02-13 19:56
Thank you, I think I understand what I need to do in terms of linking, I'll try looking into it more
I'm having trouble with actually running the example though, as it doesn't actually seem to find my Wiimote & Balance Board  until I try to manually pair them, which the readme recommends against, and then it segfaults right after. Since I feel like this thread is getting a bit messy, is there a better place I can discuss this, like on Discord or via e-mail or something? Or is continuing this issue thread fine?

**Comment by janoc** [comment] 2024-02-13 22:09
>is there a better place I can discuss this, like on Discord or via e-mail or something?
Unfortunately there isn't.

>Or is continuing this issue thread fine?
I would suggest filing a separate issue for separate problems because otherwise nobody will be able to make any sense out of it. However, before you do that ...

>When my code calls wiiuse_find and I press sync on my Wiimote or Balance Board, it also segfaults!
That is not supposed to happen.  I would suggest running the code in a debugger and trying to figure out why it segfaults. Likely some memory isn't initialized/allocated - e.g. you didn't call `wiiuse_init()` before calling `wiiuse_find()`, etc.

However, the example does that, so if it is segfaulting then something else must be going on.  Unfortunately you will have to try to debug this because I can't fix a problem I can't reproduce on a platform I don't have.

**Closed** 2024-02-15 09:11 UTC
