### ISSUE TITLE
Linux - Can't connect to Wiimote -TR

### ISSUE THREAD

**Issue by qwertychouskie** [wiiuse/wiiuse#88] opened 2016-12-13 23:47 UTC
To reproduce:
1. Compile and install Wiiuse
2. Run `wiiuseexample`
3. Press the red button on the back of the remote

The lights on the remote flash until `wiiuseexample` is killed (CTL+C) or Wiimote battery is removed, output from `wiiuseexample`:
```
wiiuse v0.15.0 loaded.
  Fork at http://github.com/rpavlik/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> http://wiiuse.net
[INFO] Found 1 bluetooth device(s).
[INFO] Found wiimote (type:  (motion plus inside)) (9C:E6:35:B3:07:97) [id 1].
[INFO] Connected to wiimote [id 1].
```
If the Wiimote battery is removed, after about 10 seconds, wiiuseexample starts spitting out:
```
[ERROR] Receiving wiimote data (id 1).
Error Details: Bad file descriptor
```
100's of times per second, like this:
![image](https://cloud.githubusercontent.com/assets/13989090/21164024/68845fbe-c14b-11e6-8ab4-2e93563838a3.png)
Master branch.

**Comment by janoc** [comment] 2016-12-14 00:22
This issue should be fixed in the yet-unmerged 'updates' branch. Could you try that one, please? -TR is the new Wiimote with an incompatible handshaking protocol. 

The "Bad file descriptor" is a red herring - that happened because you have killed the Bluetooth connection  by pulling the batteries out. The code is attempting to write into a dead socket.

**Comment by qwertychouskie** [comment] 2016-12-14 04:15
Still an issue with the updates branch.

**Comment by janoc** [comment] 2016-12-14 08:44
This might be a dupe of https://github.com/rpavlik/wiiuse/issues/21

**Comment by jeraymond** [comment] 2017-03-23 06:06
Hello, I'm also hitting this issue Linux. I did a Debug build of wiiuseexample and see this output

```
wiiuse v0.15.0 loaded.
  Fork at http://github.com/rpavlik/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> http://wiiuse.net
[INFO] Found 2 bluetooth device(s).
[INFO] Found wiimote (type:  (motion plus inside)) (40:D2:8A:B6:0A:47) [id 1].
Connecting...
[INFO] Connected to wiimote [id 1].
[INFO] A
[DEBUG] /home/jeremy/projects/wiiuse/src/wiiuse.c:356: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] /home/jeremy/projects/wiiuse/src/wiiuse.c:560: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] /home/jeremy/projects/wiiuse/src/io.c:275: Wiimote reset!

[DEBUG] (id 1) SEND: (17) 00 00 00 16 00 08
[DEBUG] (id 1) RECV: (22) 00 00 12 02 00
[DEBUG] /home/jeremy/projects/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (22) 00 00 16 02 00
[DEBUG] /home/jeremy/projects/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (22) 00 00 17 02 00
[DEBUG] /home/jeremy/projects/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
```

The wiimote sends three 0x22 reports and wiiuse is expecting 0x21. After these three reports there is not other back and forth communications. Seems like wiiuse is still waiting at this point.

I can help debug this, is there any reference anywhere to the protocol with the wiimote? What are the 0x22 reports that the wiimote is sending (how can interpret these responses)?

On OS X with the same wiimote I get a successful connection and see difference responses in the debug logs:

```
wiiuse v0.15.0 loaded.
  Fork at http://github.com/rpavlik/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> http://wiiuse.net
[DEBUG] /Users/jeremy/projects/wiiuse/src/os_mac/os_mac_find.m:200: Found a wiimote
[DEBUG] /Users/jeremy/projects/wiiuse/src/os_mac/os_mac_find.m:211: Inquiry complete, error=0, aborted=NO
[DEBUG] /Users/jeremy/projects/wiiuse/src/os_mac/os_mac_find.m:211: Inquiry complete, error=0, aborted=YES
[ERROR] Unable to stop bluetooth device inquiry.
[INFO] Found Wiimote (40-d2-8a-b6-0a-47) [id 1]
[INFO] Found 1 Wiimote device(s).
[DEBUG] /Users/jeremy/projects/wiiuse/src/os_mac/os_mac_interface.m:80: Connecting to Wiimote [id 1].
[INFO] Connected to Wiimote [id 1].
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:356: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:560: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:275: Wiimote reset!

[DEBUG] (id 1) SEND: (17) 00 00 00 16 00 08
[DEBUG] (id 1) RECV: (30) 00 00
[DEBUG] (id 1) RECV: (22) 00 00 16 07
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (21) 00 00 70 00 16 80 80 7f 32 9a 98 98 0d 00 00 00 00 00 00 00 00
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:293: Calibrated wiimote acc

[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:316: Asking for status, attempt 0 ...

[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:505: Requested wiimote status.
[DEBUG] (id 1) SEND: (15) 00
[DEBUG] (id 1) RECV: (20) 00 00 00 00 00 80
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:316: Asking for status, attempt 1 ...

[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:505: Requested wiimote status.
[DEBUG] (id 1) SEND: (15) 00
[DEBUG] (id 1) RECV: (20) 00 00 00 00 00 80
[DEBUG] /Users/jeremy/projects/wiiuse/src/io.c:316: Asking for status, attempt 2 ...

[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:505: Requested wiimote status.
[DEBUG] (id 1) SEND: (15) 00
[DEBUG] (id 1) RECV: (20) 00 00 00 00 00 80
[DEBUG] (id 1) SEND: (17) 04 a6 00 fa 00 06
[DEBUG] (id 1) RECV: (21) 00 00 50 00 fa 01 00 a4 20 00 05 00 00 00 00 00 00 00 00 00 00
[DEBUG] /Users/jeremy/projects/wiiuse/src/motion_plus.c:73: Detected inactive Motion+!
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:560: Writing 1 bytes to memory location 0x4a600f0...
Write data is: 55
[DEBUG] (id 1) SEND: (16) 04 a6 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:560: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:560: Writing 1 bytes to memory location 0x4a400fb...
Write data is: 0
[DEBUG] (id 1) SEND: (16) 04 a4 00 fb 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:356: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:356: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:356: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30
Connected to 1 wiimotes (of 1 found).
[DEBUG] (id 1) SEND: (11) 10
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:217: Starting rumble...
[DEBUG] (id 1) SEND: (13) 11
[DEBUG] /Users/jeremy/projects/wiiuse/src/wiiuse.c:221: Stopping rumble...
[DEBUG] (id 1) SEND: (13) 10

Controls:
	B toggles rumble.
	+ to start Wiimote accelerometer reporting, - to stop
	UP to start IR camera (sensor bar mode), DOWN to stop.
	1 to start Motion+ reporting, 2 to stop.
```

**Comment by janoc** [comment] 2017-03-23 08:51
Hello @jeraymond 

This looks like something is going wrong with the Linux BT stack or something. Wiiuse asks for reading something from the  Wiimote's memory (outgoing report 17), probably accelerometer calibration data, and the Wiimote never sends the data back, only ACKs the request, saying there is no error (bogus report 22 which has one byte too many?). Wiiuse then keeps waiting for the report 21 which never comes :(

On your Mac the report 17 elicits the response by report 21 right away (and there is no spurious report 22 being generated) and everything goes fine.

The protocol is described here:
http://wiibrew.org/wiki/Wiimote

Honestly, I am a bit at loss about what to do - if the hw doesn't generate the right reports when prompted, I have no idea how to fix it. Did you pair your Wiimote to Linux or Mac? Or are you using it unpaired, by using the red button in the battery compartment?

**Comment by jeraymond** [comment] 2017-03-23 14:20
On both Linux and Mac I used the red button to connect. So not paired (i.e. did not hold down the 1, 2 buttons to pair it). Perhaps trying pairing via 1,2 buttons on Linux?

I have two wiimotes one original HW (without the built-in MotionPlus inside) and one with the built-in MotionPlus. The original HW wiimote is able to connect (via the red button) to both Linux and Mac. The -RT remote with built-in motion plus connects fine to the Mac via red button but not with Linux.

**Comment by janoc** [comment] 2017-03-23 14:31
On Thu, Mar 23, 2017 at 3:20 PM, Jeremy Raymond <notifications@github.com>
wrote:

> On both Linux and Mac I used the red button to connect. So not paired
> (i.e. did not hold down the 1, 2 buttons to pair it). Perhaps trying
> pairing via 1,2 buttons on Linux?
>

That doesn't do pairing. It only puts the Wiimote into discoverable mode
(on the non -TR one) or does nothing (on the -TR one) apart from waking it
up. Pairing requires a connection to the Wiimote and sending reversed MAC
address as a pairing code. I am mentioning it only because some utilities
allow to do it today, also gadgets like the Mayflash DolphinBar.


> I have two wiimotes one original HW (without the built-in MotionPlus
> inside) and one with the built-in MotionPlus. The original HW wiimote is
> able to connect (via the red button) to both Linux and Mac. The -RT remote
> with built-in motion plus connects fine to the Mac via red button but not
> with Linux.
>

Just for clarity - there are 3 (at least) types of Wiimotes. The original
one, the original with built-in MotionPlus and the last generation which
has the built-in MotionPlus & the -TR suffix in the Bluetooth ID. Having
the built-in MotionPlus *is not* a sign that you have a -TR Wiimote. E.g. I
have one genuine Nintendo non-TR Wiimote with MotionPlus built-in.

So this seems to be some sort of bad interaction between the Linux BT stack
and the -TR wiimote :( One thing to try in Linux would be to try to put a
delay before the accelerometer calibration is being read (the 0x17 report)
and see whether it changes anything. The Linux BT stack is very fast and
sometimes the messages are sent too quickly for the Wiimote. When that
happens the Wiimote goes into an undefined state and all bets are off.

**Comment by jeraymond** [comment] 2017-03-24 03:12
I tried adding the delay (in a few places before sending/reading) but that didn't do the trick. I still got the same output. Any other suggestions?

**Comment by janoc** [comment] 2017-03-24 13:18
Hmm, could you perhaps try to single-step through the code? Put a breakpoint at "step 1 - calibration of accelerometers" (around line 282 in io.c) and see whether the wiiuse_read_data_sync() returns something.

Another thing that is odd is that the timeout feature isn't working right - normally if there is no reply received within 5 seconds it is supposed to retry. But that code could well be buggy, because I don't have any hw to test it with :(

**Comment by jeraymond** [comment] 2017-03-25 00:40
The process hangs at this `read` call.

https://github.com/rpavlik/wiiuse/blob/master/src/os_nix.c#L349

```c
int wiiuse_os_read(struct wiimote_t* wm, byte* buf, int len) {
	int rc;
	int i;

	rc = read(wm->in_sock, buf, len); // Hangs here
```

Is this a call to the bluetooth stack to read (where is this defined)? I can 'unstick' it by resetting the wiimote at which point I get a disconnected response (`0`) back. Any way to put a timeout on this call?

**Comment by janoc** [comment] 2017-03-25 00:52
read() is a system call, it is trying to read data from the Bluetooth socket. It is meant to block until some data arrive. 

There is no way to put a timeout on this (and there shouldn't be one), at least not without a lot of re-engineering of how the library works. Where does it get called from? From waiting for the report 21?

**Comment by jeraymond** [comment] 2017-03-25 01:11
Yes, that's correct. 

https://github.com/rpavlik/wiiuse/blob/master/src/io.c#L282
```
	/* step 1 - calibration of accelerometers */
	{
		struct accel_t* accel = &wm->accel_calib;

		wiiuse_read_data_sync(wm, 1, WM_MEM_OFFSET_CALIBRATION, 8, buf); // Does not return
```

After 3 of these it hangs:
(id 1) dropping report 0x22, waiting for 0x21

**Comment by janoc** [comment] 2017-03-25 01:17
So that means the Wiimote doesn't like something and gets confused. Sends 3 acks for report we didn't send and doesn't send a reply we need to proceed. The worst thing is that exactly the same exchange is used on your Mac, so it has to be something low level.   I am starting to suspect that the Linux BT stack mangles an outgoing report :( 

I am not quite sure what more we can try. Perhaps you could try to obtain a trace using hcidump to see what exactly is happening on the Bluetooth level, but I am afraid that will be quite messy to decode. This post shows how to obtain and decode a trace using hcidump and Wireshark:
http://mobilesociety.typepad.com/mobile_life/2014/01/tracing-bluetooth-with-wireshark-and-hcidump.html

**Comment by jeraymond** [comment] 2017-03-25 01:21
I tried by passing the entire `void wiiuse_handshake(struct wiimote_t* wm, byte* data, uint16_t len)` function and it proceeded to the point where the `wiiuseexample` app could receive button presses and cause the wiimote to rumble. There is something in the handshake it doesn't like.

Does this same `void wiiuse_handshake(struct wiimote_t* wm, byte* data, uint16_t len) ` get used on both Linux and on the Mac? I see there are some #ifdef WIIUSE_SYNC_HANDSHAKE around there.

**Comment by janoc** [comment] 2017-03-25 10:08
That's weird :( If you bypass the entire handshake, then things won't get initialized correctly - e.g. the accelerometer won't be calibrated, expansions detected, etc. 

I have checked whether the code is the same between Linux and Mac and I believe it is - the WIIUSE_SYNC_HANDSHAKE is defined wiiuse.h (check your version to be sure). In any case, your traces show that the data the were sent and received were exactly the same up to the moment the accelerometer calibration has started. Then something got confused there. 

What is certainly different is the low level code, the Mac BT API is completely different from what Linux uses. That's why it would be really useful to see the actual Bluetooth traffic between the Wiimote and the host. It is possible that some of the Linux socket flags used are causing issues.

**Comment by jeraymond** [comment] 2017-03-25 15:30
Bypassing the handshake allowed for button press events to be received from the wiimote but you're right the accelerometer and IR data was not working. I can also confirm the Mac does also go through the same `wiiuse_handshake()` function, the difference being how the data actually get sent to the device at a lower level (in different `wiiuse_os_write()` functions).

I was perusing the [WiiBrew](http://wiibrew.org/wiki/Wiimote#Status_Reporting) docs I noticed (in the HID Interface section)

> ... PSM 0x11 for the control pipe and PSM 0x13 for the data pipe ... The original Wiimotes (RVL-CNT-01) allowed sending commands using SET REPORT (0x52) over the control pipe, instead of using the data pipe; however, this form does not work on the newer RVL-CNT-01-TR, and as such is not recommended.

In `os_nix.c` the `wiiuse_os_write()` function uses `wf->out_sock` which is initialized to the control pipe `WM_OUTPUT_CHANNEL 0x11` in `wiiuse_os_connect_single()`. The `wf->in_sock` is initialed to the data pipe `WM_INPUT_CHANNEL 0x13` and is used by the wiiuse_os_read()`. Could it be that `wiiuse_set_report_type` is sending over 0x11 but for the -TR should be the 0x13?

**Comment by janoc** [comment] 2017-03-25 20:00
Yes, the buttons don't need any init, but the accelerometer needs calibration to have the data correctly scaled and the IR camera needs some initialization, so it is normal that it won't work. 

Hmm, the find about the PSM is interesting. I vaguely remember seeing this note too. I think the problem is not the wiiuse_set_report but but the wiiuse_read_data_sync which needs to send the request over the data pipe. 

Could you test it? However, if you change wiiuse_os_write() to write using the 0x13, it is likely to break some other things that use that function too (some stuff needs to go over the control pipe, not data pipe). 

This could be an enormous drag to fix, actually - like the wiiuse_os_write/wiiuse_os_read would need to have an extra parameter specifying which pipe to operate on and the higher level code refactored accordingly. I wonder what @rpavlik thinks about this.

**Comment by janoc** [comment] 2017-03-25 20:16
Edit: I am digging trough the Mac code and it seems to send everything over PSM 0x13 (the interrupt channel). So maybe that could explain the difference.

Could you test whether changing the socket used by wiiuse_os_write() fixes it in Linux?

**Comment by jeraymond** [comment] 2017-03-25 23:48
Simply change the socket in `wiiuse_os_write()` didn't work (and broke working with the original remote). There must be some things that must go over the 0x11 socket.

**Comment by janoc** [comment] 2017-03-26 00:09
That's what I have thought. I guess a separate version of this function needs to be made for this specific case.

**Comment by qwertychouskie** [comment] 2018-11-21 01:44
Confirmed to still be an issue with 0.15.1.

```
qwerty@qwerty-Inspiron-3520:~/STK/wiiuse/build$ ./example/wiiuseexample
wiiuse v0.15.1 loaded.
  Fork at http://github.com/rpavlik/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> http://wiiuse.net
[INFO] Found 1 bluetooth device(s).
[INFO] Found wiimote (type:  (motion plus inside)) (B8:AE:6E:23:BC:46) [id 1].
[INFO] Connected to wiimote [id 1].
[DEBUG] /home/qwerty/STK/wiiuse/src/wiiuse.c:356: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30 
[DEBUG] /home/qwerty/STK/wiiuse/src/wiiuse.c:560: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55 
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:275: Wiimote reset!

[DEBUG] (id 1) SEND: (17) 00 00 00 16 00 08 
[DEBUG] (id 1) RECV: (20) 00 00 42 00 00 9e 00 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:140: (id 1) dropping report 0x20, waiting for 0x21
[DEBUG] (id 1) RECV: (22) 00 00 12 02 9e 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (22) 00 00 16 02 00 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (22) 00 00 17 02 00 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
^C
qwerty@qwerty-Inspiron-3520:~/STK/wiiuse/build$ 
```

If there's anything I can do, please let me know.  I'm not sure how to change `wiiuse_os_write()`.

**Comment by janoc** [comment] 2018-11-21 10:00
Hi, 

I am can only theorize here, because I don't have the hw to test this, but you could try to do a hack in the wiiuse_os_write() testing whether the report_type is 0x50 or 0x52 (Wiibrew seems to indicate this, but we are only using 0x50?) and if it is, send the request out over wm->in_sock instead of wm->out_sock. 

I.e. replace this:
```
	rc = write(wm->out_sock, write_buffer, len + 2);
```
with:
```
        if(report_type == 0x50 || report_type == 0x52)
            rc = write(wm->in_sock, write_buffer, len + 2);
        else
            rc = write(wm->out_sock, write_buffer, len + 2);
```

And check if it changes anything.

**Comment by qwertychouskie** [comment] 2018-11-22 19:13
@janoc I used:

```
    if (report_type == 0x50 || report_type == 0x52) {
        printf("using in_sock\n");
        rc = write(wm->in_sock, write_buffer, len + 2);
    } else {
        printf("using out_sock\n");
        rc = write(wm->out_sock, write_buffer, len + 2);
    }
```

Output:
```
qwerty@qwerty-Inspiron-3520:~/STK/wiiuse/build$ ./example/wiiuseexample
wiiuse v0.15.1 loaded.
  Fork at http://github.com/rpavlik/wiiuse
  Original By: Michael Laforest <thepara[at]gmail{dot}com> http://wiiuse.net
[INFO] Found 1 bluetooth device(s).
[INFO] Found wiimote (type:  (motion plus inside)) (B8:AE:6E:23:BC:46) [id 1].
[INFO] Connected to wiimote [id 1].
[DEBUG] /home/qwerty/STK/wiiuse/src/wiiuse.c:356: Setting report type: 0x30
[DEBUG] (id 1) SEND: (12) 00 30 
using out_sock
[DEBUG] /home/qwerty/STK/wiiuse/src/wiiuse.c:560: Writing 1 bytes to memory location 0x4a400f0...
Write data is: 55 
[DEBUG] (id 1) SEND: (16) 04 a4 00 f0 01 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
using out_sock
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:275: Wiimote reset!

[DEBUG] (id 1) SEND: (17) 00 00 00 16 00 08 
using out_sock
[DEBUG] (id 1) RECV: (20) 00 00 42 00 00 8f 00 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:140: (id 1) dropping report 0x20, waiting for 0x21
[DEBUG] (id 1) RECV: (22) 00 00 12 02 8f 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (22) 00 00 16 02 00 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
[DEBUG] (id 1) RECV: (22) 00 00 17 02 00 
[DEBUG] /home/qwerty/STK/wiiuse/src/io.c:140: (id 1) dropping report 0x22, waiting for 0x21
^C
qwerty@qwerty-Inspiron-3520:~/STK/wiiuse/build$
```

It looks like it never uses the `in_sock` here.

**Comment by rpavlik** [comment] 2018-11-22 20:47
Hmm, looks like I forgot to update the URL in the source, too.

Yeah I don't have a "with motion plus" wiimote either, sorry.

**Comment by janoc** [comment] 2018-11-22 22:58
I am digging into the code, this whole socket issue may be a complete red herring because the SET REPORT HID command isn't used during the handshake. So there has to be something more to it.

@rpavlik it is not the wiimote "with motion plus" - that one actually works fine (I have one). It is the last type that reports itself with -TR suffix in the device name. It also has a motion plus built-in but different firmware. And it is a pain in the backside because it is not marked on the box, so no idea which variant you get until you turn it on. Given that these things are still selling for 40-60€ here (everything cheaper are clones) I am not very eager to go out and start shopping for one of these.

**Comment by janoc** [comment] 2018-11-24 11:34
OK, I took one for the team and bought another Wiimote for 50€ and can finally reproduce the problem. Yay! 

It is nuts that Nintendo is still selling these things for such insane prices, 12 years since they were introduced and past two console generations, both dead now :(

**Comment by qwertychouskie** [comment] 2018-11-24 22:55
Thanks for your contribution!

I'd hardly call the Wii/Wii U "dead", many games (e.g. Smash Bros) haven't had their Switch version released yet.

**Comment by janoc** [comment] 2018-11-24 23:08
Well, dead as in not manufactured/sold anymore. 
BTW, I think I have fixed the -TR wiimote, a code to test will be posted shortly.

**Comment by janoc** [comment] 2018-11-24 23:52
@qwertychouskie could you try this version, please? 
https://github.com/janoc/wiiuse/tree/handshake-test

If it works, I will merge that.

**Comment by qwertychouskie** [comment] 2018-11-25 03:42
The example seems to work best I can tell, testing in SuperTuxKart now.

**Comment by qwertychouskie** [comment] 2018-11-25 05:34
Confirmed to work in SuperTuxKart with tilt steering!

**Closed** 2018-11-25 10:49 UTC

**Comment by qwertychouskie** [comment] 2018-11-26 17:36
Thanks so much!

**Comment by janoc** [comment] 2018-11-26 17:43
You are welcome.
